#!/bin/bash

# Source:

# Add all users to "lpadmin" group. Useful to allow users to add/remove and
# restore paused printers.

# Run as root
/usr/sbin/dseditgroup -o edit -n /Local/Default -a everyone -t group lpadmin
