#!/bin/bash

# Add text to login screen

# Text to add:
TEXT_TO_ADD="Hands off my computer! :)"

# Run as root
sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "$TEXT_TO_ADD"
