#!/bin/bash

# Run as root in Apple Remote Desktop

#  navigate to Autoupdate folder
cd /Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS

#  install updates
./msupdate --install
